name: Moveetic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.0
  - numpy=1.26.3
  - scikit-learn=1.4.0
  - pip
  - pip:
      - fastapi==0.109.0
      - uvicorn[standard]==0.27.0
      - pydantic==2.5.3
      - sentence-transformers==3.3.1
      - torch  
      - pyarrow
      - watchfiles